spring:
  application:
    name: java_training

  datasource:
    #    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/java_training?useSSL=false&serverTimezone=UTC}
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://java_training_xox0_user:gdZu2no1wkGj2qMJPu79AGC7daoMlzjf@dpg-d55l813uibrs7394ejig-a.oregon-postgres.render.com/java_training_xox0}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 20
      maximum-pool-size: 100
      idle-timeout: 10000
      pool-name: connection-pool
      auto-commit: false
      max-lifetime: 72000

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        #        dialect: org.hibernate.dialect.MySQLDialect
        dialect: org.hibernate.dialect.PostgreSQLDialect

  batch:
    job:
      enabled: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

server:
  port: ${PORT:8081}

jwt:
  secret: ${JWT_SECRET:a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6}
  expiration: 3600000
